CREATE DATABASE customer_shopping_behavior;
USE customer_shopping_behavior;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM cleaned_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM cleaned_data
WHERE discount_applied='yes' AND purchase_amount>=( SELECT AVG(purchase_amount) FROM cleaned_data);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,review_rating
FROM cleaned_data
WHERE review_rating>=(SELECT AVG(review_rating) FROM cleaned_data)
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, AVG(purchase_amount)
FROM cleaned_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) as total_customers,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM cleaned_data
GROUP BY subscription_status
ORDER BY avg_spend,total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
(SUM(CASE WHEN discount_applied='YES' THEN 1 ELSE 0 END)/(COUNT(*)) * 100) AS discount_rate
FROM cleaned_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
--  and show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
     WHEN previous_purchases =1 THEN ' NEW'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
     ELSE 'LOYAL'
     END AS customer_segment
FROM cleaned_data
)
SELECT customer_segment, COUNT(*) AS 'No. of customer'
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
 WITH item_counts AS (
 SELECT category, item_purchased,
 COUNT(customer_id) AS total_orders,
 ROW_NUMBER() OVER ( PARTITION BY category 
 ORDER BY COUNT(customer_id) DESC) AS item_rank
 FROM cleaned_data
 GROUP BY category, item_purchased
 )
SELECT item_rank , category, item_purchased , total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeated_buyers
FROM cleaned_data
WHERE previous_purchases > 5
GROUP BY  subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM cleaned_data
GROUP BY age_group
ORDER BY total_revenue DESC;

FLUSH privileges;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Pihu@12345';
FLUSH PRIVILEGES;